#!/bin/sh

case "$1" in
    *.tar*) tar tf "$1";;
    *.zip) lsar "$1";;
    *.rar) lsar l "$1";;
    *.7z) 7z l "$1";;
    *.pdf) pdftotext "$1" -;;
    *.jpg) exiftool "$1";;
    *.jpeg) exiftool "$1";;
    *.png) exiftool "$1";;
    *.mp4) exiftool "$1";;
    *.mkv) exiftool "$1";;
    *.webm) exiftool "$1";;
    *) highlight -O ansi "$1" || cat "$1";;
esac

